# Copyright (c) 2026 Semtech Corporation
# SPDX-License-Identifier: Apache-2.0
# Created by Charles-Henri Hallard (charles@evolyenergy.com)

# Disable the native Zephyr LoRa driver — USP uses its own STM32WL HAL
CONFIG_LORA=n
CONFIG_SEMTECH_SX126X=n

# USP STM32WL internal radio driver
CONFIG_SEMTECH_SX126X_STM32WL=y

CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
